### ISSUE TITLE
EXPOSED API KEY!!!!!!!!!!

### ISSUE THREAD

**Issue by ssebastianoo** [LukeGotBored/boopnews#1]
⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠
https://github.com/LukeGotBored/boopnews/blob/42215acdafab41e63586f1c234e5de07798cb4cf/script.js#L105
⚠⚠⚠⚠⚠⚠⚠⚠⚠⚠

**Comment by LukeGotBored** [comment]
Thank you, I've replaced the expired api key with a placeholder value
